config/routes.rb
Rails.application.routes.draw do
  resources :cell_phones
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cell_phone.rb
class CellPhone < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/cell_phones_controller.rb
class CellPhonesController < ApplicationController
  before_action :set_cell_phone, only: [:show, :edit, :update, :destroy]

  # GET /cell_phones
  # GET /cell_phones.json
  def index
    @cell_phones = CellPhone.all
  end

  # GET /cell_phones/1
  # GET /cell_phones/1.json
  def show
  end

  # GET /cell_phones/new
  def new
    @cell_phone = CellPhone.new
  end

  # GET /cell_phones/1/edit
  def edit
  end

  # POST /cell_phones
  # POST /cell_phones.json
  def create
    @cell_phone = CellPhone.new(cell_phone_params)

    respond_to do |format|
      if @cell_phone.save
        format.html { redirect_to @cell_phone, notice: 'Cell phone was successfully created.' }
        format.json { render :show, status: :created, location: @cell_phone }
      else
        format.html { render :new }
        format.json { render json: @cell_phone.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cell_phones/1
  # PATCH/PUT /cell_phones/1.json
  def update
    respond_to do |format|
      if @cell_phone.update(cell_phone_params)
        format.html { redirect_to @cell_phone, notice: 'Cell phone was successfully updated.' }
        format.json { render :show, status: :ok, location: @cell_phone }
      else
        format.html { render :edit }
        format.json { render json: @cell_phone.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cell_phones/1
  # DELETE /cell_phones/1.json
  def destroy
    @cell_phone.destroy
    respond_to do |format|
      format.html { redirect_to cell_phones_url, notice: 'Cell phone was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cell_phone
      @cell_phone = CellPhone.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def cell_phone_params
      params.require(:cell_phone).permit(:model, :version)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cell_phones_helper.rb
module CellPhonesHelper
end

app/views/cell_phones/_form.html.erb
<%= form_for(cell_phone) do |f| %>
  <% if cell_phone.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(cell_phone.errors.count, "error") %> prohibited this cell_phone from being saved:</h2>

      <ul>
      <% cell_phone.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :model %>
    <%= f.text_field :model %>
  </div>

  <div class="field">
    <%= f.label :version %>
    <%= f.text_field :version %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/cell_phones/edit.html.erb
<h1>Editing Cell Phone</h1>

<%= render 'form', cell_phone: @cell_phone %>

<%= link_to 'Show', @cell_phone %> |
<%= link_to 'Back', cell_phones_path %>

app/views/cell_phones/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Cell Phones</h1>

<table>
  <thead>
    <tr>
      <th>Model</th>
      <th>Version</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @cell_phones.each do |cell_phone| %>
      <tr>
        <td><%= cell_phone.model %></td>
        <td><%= cell_phone.version %></td>
        <td><%= link_to 'Show', cell_phone %></td>
        <td><%= link_to 'Edit', edit_cell_phone_path(cell_phone) %></td>
        <td><%= link_to 'Destroy', cell_phone, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Cell Phone', new_cell_phone_path %>

app/views/cell_phones/new.html.erb
<h1>New Cell Phone</h1>

<%= render 'form', cell_phone: @cell_phone %>

<%= link_to 'Back', cell_phones_path %>

app/views/cell_phones/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Model:</strong>
  <%= @cell_phone.model %>
</p>

<p>
  <strong>Version:</strong>
  <%= @cell_phone.version %>
</p>

<%= link_to 'Edit', edit_cell_phone_path(@cell_phone) %> |
<%= link_to 'Back', cell_phones_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PickAPhone</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>